server:
  port: 8190
  servlet:
    context-path: /winter-carts
integrations:
  product-service:
    url: http://localhost:8189/winter-app/
    connect-timeout: 5000
    read-timeout: 10000
    write-timeout: 5000
