server:
  port: 5555
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
            allowedHeaders: "*"
      routes:
        - id: core-service
          uri: http://localhost:8189/
          predicates:
            - Path=/winter-market-app/**
          filters:
            - StripPrefix=1
            - PrefixPath=/winter-market-app
            - JwtAuthFilter
        - id: cart-service
          uri: http://localhost:8190/
          predicates:
           - Path=/winter-market-carts/**
          filters:
            - StripPrefix=1
            - PrefixPath=/winter-market-carts
            - JwtAuthFilter
        - id: auth-service
          uri: http://localhost:8188/
          predicates:
            - Path=/winter-market-auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/winter-market-auth
            - JwtAuthFilter

jwt:
  secret: h4f8093h4f983yhrt9834hr0934hf0hf493g493gf438rh438th34g34g

